DROP PROCEDURE attachResponsibleToMinor,
               insertUser,
               insertActivity,
               insertAvatar,
               insertCategory,
               insertDocument,
               insertLogoStructure,
               insertPictureActivity,
               insertRole,
               insertStructure,
               insertTypeStructure,
               reservation,
               updateUser,
               updateRoleUser,
               updateAdministrator;

DROP FUNCTION insertUpdatePerson,
              insertUpdateMemberData,
              insertUpdateMember,
              insertMemberminor,
              insertMemberAdult,
              insertAddress,
              displayOneMemberPair,
              displayOneMember,
              displayChildrenOfMember,
              displayAllMemberById;
